export enum  ListAction{
    SET_LISTS = 'SET_LISTS',
    SET_ITEMS_IN_LIST = 'SET_ITEMS_IN_LIST',
    ADD_TO_LISTS ='ADD_TO_LISTS',
    EDIT_NAME_LIST ='EDIT_NAME_LIST',
    DELETE_LIST ='DELETE_LIST',
}