export enum ListAction {
    SET_LISTS = "SET_LISTS",
    SET_ITEMS_IN_LIST = "SET_ITEMS_IN_LIST",
    ADD_TO_LISTS = "ADD_TO_LISTS",
    ADD_ITEM_TO_LIST = "ADD_ITEM_TO_LIST",
    EDIT_NAME_LIST = "EDIT_NAME_LIST",
    DELETE_LIST = "DELETE_LIST",
    ADD_ITEM_TO_BASKET = "ADD_ITEM_TO_BASKET",
    REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET",
    CLEAR_BASKET = "CLEAR_BASKET",
}