export enum RecipeAction {
  SET_RECIPES = 'SET_RECIPES',
  SET_ITEM_IN_RECIPES = 'SET_ITEM_IN_RECIPES',
  ADD_RECIPE = 'ADD_RECIPE',
  EDIT_RECIPE = 'EDIT_RECIPE',
  EDIT_DESCRIPTION_IN_RECIPE = 'EDIT_DESCRIPTION_IN_RECIPE',
  DELETE_RECIPE = 'DELETE_RECIPE',
  DELETE_ITEM_IN_RECIPE = 'DELETE_ITEM_IN_RECIPE',
  ADD_ITEM_TO_RECIPE = 'ADD_ITEM_TO_RECIPE',
  EDIT_ITEM_IN_RECIPE = 'EDIT_ITEM_IN_RECIPE',
}
